### ISSUE TITLE
"commit & custom push" does not show the push dialog for intellij versions > 243

### ISSUE THREAD

**Issue by EvoGroupTN** [EvoGroupTN/push-with-options-intellij-plugin#3]
For some intellij versions (maybe > 243 ) the push dialog is not shown (maybe due to some intellij api changes/restrictions ?). To check

**Comment by e-belair** [comment]
Seems to not working in Phpstorm 
PhpStorm 2024.3.5
Build #PS-243.26053.13, built on March 12, 2025

**Comment by EvoGroupTN** [comment]
Hello @e-belair can you give more details on which part is not working? if it's the same issue described here (the push dialog does not appear after clicking "cmmit & custom push") then it's "normal" cause it's due to some idea api versions incompatibility with native git4idea plugin which manage git commands. Trying to fix that asap

**Comment by EvoGroupTN** [comment]
Fixed in v2.2.0

**Comment by e-belair** [comment]
Hi, still not working on PhpStorm 2024.3.5 Build #PS-243.26053.13

When I click on the button, nothing happens.
I have the v2.2.0

**Comment by EvoGroupTN** [comment]
Hi @e-belair thanks for your feedback. Did you restart PS after updating/installing the plugin? I've made some tests with PS 2024.3.5 and it works for me.

**Comment by e-belair** [comment]
yeah I've restarted PS, created a .push-options file with some options, but nothing happens.

**Comment by EvoGroupTN** [comment]
Ah bien vu. I'll check the modal view compatibility issue tonight. Thanks for the feedback

**Comment by e-belair** [comment]
Seems that the modal commit interface has benn moved into a plugin

**Comment by EvoGroupTN** [comment]
yes this option was removed from the default settings https://plugins.jetbrains.com/plugin/26647-git-modal-commit-interface
